services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['sh', '-c', 'npm ci --dev && ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"']
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/usr/src/app
    environment:
      SECRET_KEY: "${SECRET_KEY:-changeme}"
      DEBUG: "true"
    ports:
      - 8000:8000
    depends_on:
      pg_db:
        condition: service_healthy
    command: ["sh", "-c", "pip3 install -r requirements.txt && python3 manage.py collectstatic --no-input && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]
