version: '3.8'
services:
    frontend:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - 3000:3000
            - 1234:1234
        stdin_open: true
        tty: true
