# Generated by Django 3.2.15 on 2024-05-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20240507_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
