# Generated by Django 3.2.15 on 2024-05-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_order_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_lastname',
            new_name='lastname',
        ),
    ]
