# Generated by Django 3.2.15 on 2024-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-registrated_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='registrated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(null=True, verbose_name='Дата звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Необработан'), ('IN_PROG', 'В обработке'), ('READY', 'Готов к выдаче'), ('DONE', 'Выполнен'), ('CANCELLED', 'Отменен')], db_index=True, default='CREATED', max_length=10, verbose_name='статус'),
        ),
    ]
