# Generated by Django 3.2.15 on 2024-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20240510_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('CASH', 'Наличные'), ('CARD', 'Карта'), ('ELECT', 'Электронно')], default='NONE', max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cоздан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Необработан'), (2, 'В обработке'), (3, 'Готов к выдаче'), (4, 'Выполнен'), (5, 'Отменен')], db_index=True, default=1, max_length=10, verbose_name='статус'),
        ),
    ]
