# Generated by Django 3.2.15 on 2024-05-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20240510_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Необработан'), ('2', 'В обработке'), ('3', 'Готов к выдаче'), ('4', 'Выполнен'), ('5', 'Отменен')], db_index=True, default=1, max_length=1, verbose_name='статус'),
        ),
    ]
