# Generated by Django 3.2.15 on 2024-05-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-registered_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='registrated_at',
            new_name='registered_at',
        ),
    ]
