# Generated by Django 3.2.15 on 2024-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
